"""
db.py — Persistent storage layer

Uses Supabase when SUPABASE_URL + SUPABASE_KEY are in st.secrets or env vars.
Falls back to local JSON files so local development works without any setup.
"""
import json
import logging
import os
from datetime import datetime, timezone
from pathlib import Path

logger = logging.getLogger(__name__)

ROOT = Path(__file__).parent
_PAPER_TRADES_JSON = ROOT / "paper_trades.json"
_POSITIONS_JSON    = ROOT / "kalshi" / "positions_kalshi.json"
_CALIBRATION_JSON  = ROOT / "model_crypto_calibration.json"

# ── Supabase client (singleton) ────────────────────────────────────────────────
_client = None

def _get_client():
    global _client
    if _client is not None:
        return _client

    url = key = None
    try:
        import streamlit as st
        url = st.secrets.get("SUPABASE_URL")
        key = st.secrets.get("SUPABASE_KEY")
    except Exception:
        pass
    if not url:
        url = os.environ.get("SUPABASE_URL")
        key = os.environ.get("SUPABASE_KEY")

    if url and key:
        try:
            from supabase import create_client
            _client = create_client(url, key)
            logger.info("Supabase connected")
        except Exception as e:
            logger.warning(f"Supabase init failed: {e}")
    return _client


# ── JSON fallback helpers ──────────────────────────────────────────────────────
def _load_json(path: Path) -> list:
    if not path.exists():
        return []
    with open(path) as f:
        return json.load(f)

def _save_json(path: Path, data) -> None:
    with open(path, "w") as f:
        json.dump(data, f, indent=2)


# ── Paper trades ───────────────────────────────────────────────────────────────
def load_paper_trades() -> list[dict]:
    client = _get_client()
    if client:
        try:
            resp = (client.table("paper_trades")
                    .select("*")
                    .order("placed_at", desc=False)
                    .execute())
            return resp.data or []
        except Exception as e:
            logger.warning(f"load_paper_trades failed: {e}")
    return _load_json(_PAPER_TRADES_JSON)


def add_paper_trade(trade: dict) -> None:
    """Insert one new paper trade. The 'id' field is auto-generated by Supabase."""
    client = _get_client()
    if client:
        try:
            row = {k: v for k, v in trade.items() if k != "id"}
            client.table("paper_trades").insert(row).execute()
            return
        except Exception as e:
            logger.warning(f"add_paper_trade failed: {e}")
    trades = _load_json(_PAPER_TRADES_JSON)
    trades.append(trade)
    _save_json(_PAPER_TRADES_JSON, trades)


def reopen_paper_trade(trade_id: str) -> None:
    """Reset a paper trade back to open (undoes an incorrect auto-settle)."""
    updates = {"status": "open", "result": None, "pnl_dollars": None}
    client = _get_client()
    if client:
        try:
            client.table("paper_trades").update(updates).eq("id", trade_id).execute()
            return
        except Exception as e:
            logger.warning(f"reopen_paper_trade failed: {e}")
    trades = _load_json(_PAPER_TRADES_JSON)
    for t in trades:
        if t.get("id") == trade_id:
            t["status"] = "open"
            t.pop("result", None)
            t.pop("pnl_dollars", None)
    _save_json(_PAPER_TRADES_JSON, trades)


def settle_paper_trade(trade_id: str, result: str, pnl: float) -> None:
    """Mark a paper trade settled with result + P&L. Matches by Supabase UUID id."""
    updates = {"status": "settled", "result": result, "pnl_dollars": pnl}
    client = _get_client()
    if client:
        try:
            client.table("paper_trades").update(updates).eq("id", trade_id).execute()
            return
        except Exception as e:
            logger.warning(f"settle_paper_trade failed: {e}")
    trades = _load_json(_PAPER_TRADES_JSON)
    for t in trades:
        if t.get("id") == trade_id:
            t.update(updates)
    _save_json(_PAPER_TRADES_JSON, trades)


# ── Position overrides ─────────────────────────────────────────────────────────
def load_position_overrides() -> dict[str, dict]:
    """Returns {ticker: {ticker, contracts, entry_cents, stop_cents}}"""
    client = _get_client()
    if client:
        try:
            resp = client.table("position_overrides").select("*").execute()
            return {row["ticker"]: row for row in (resp.data or [])}
        except Exception as e:
            logger.warning(f"load_position_overrides failed: {e}")
    rows = _load_json(_POSITIONS_JSON)
    if isinstance(rows, list):
        return {r["ticker"]: r for r in rows if "ticker" in r}
    return {}


def save_position_overrides(overrides: dict[str, dict]) -> None:
    """Upsert all position overrides keyed by ticker."""
    client = _get_client()
    if client:
        try:
            now  = datetime.now(timezone.utc).isoformat()
            rows = [
                {
                    "ticker"      : ticker,
                    "contracts"   : data.get("contracts"),
                    "entry_cents" : data.get("entry_cents", 0),
                    "stop_cents"  : data.get("stop_cents", 0),
                    "updated_at"  : now,
                }
                for ticker, data in overrides.items()
            ]
            if rows:
                client.table("position_overrides").upsert(rows).execute()
            return
        except Exception as e:
            logger.warning(f"save_position_overrides failed: {e}")
    _save_json(_POSITIONS_JSON, list(overrides.values()))


# ── Calibration ────────────────────────────────────────────────────────────────
def load_calibration_db() -> dict | None:
    client = _get_client()
    if client:
        try:
            resp = (client.table("calibration")
                    .select("data")
                    .eq("id", 1)
                    .execute())
            if resp.data:
                return resp.data[0]["data"]
        except Exception as e:
            logger.warning(f"load_calibration_db failed: {e}")
    if _CALIBRATION_JSON.exists():
        with open(_CALIBRATION_JSON) as f:
            return json.load(f)
    return None


def save_calibration_db(data: dict) -> None:
    client = _get_client()
    if client:
        try:
            client.table("calibration").upsert({
                "id"        : 1,
                "data"      : data,
                "updated_at": datetime.now(timezone.utc).isoformat(),
            }).execute()
            return
        except Exception as e:
            logger.warning(f"save_calibration_db failed: {e}")
    _save_json(_CALIBRATION_JSON, data)
