"""
kalshi/db.py — Kalshi-side persistence layer.

Owns Supabase tables: paper_trades, kalshi_trades, position_overrides,
feature_flags, calibration. Falls back to local JSON if Supabase is
unavailable.
"""
import logging
import sys
from datetime import datetime, timezone
from pathlib import Path

# Ensure repo root is importable so `shared` resolves regardless of how this
# module is loaded (Streamlit Cloud, `python kalshi/scan_cron.py`, pytest, etc.)
_REPO_ROOT = Path(__file__).parent.parent
if str(_REPO_ROOT) not in sys.path:
    sys.path.insert(0, str(_REPO_ROOT))

from shared.db_common import _get_client, _load_json, _save_json

logger = logging.getLogger(__name__)

ROOT = Path(__file__).parent
_PAPER_TRADES_JSON = ROOT / "paper_trades.json"
_POSITIONS_JSON    = ROOT / "positions_kalshi.json"
_CALIBRATION_JSON  = ROOT / "model_crypto_calibration.json"


# ── Paper trades ───────────────────────────────────────────────────────────────
def load_paper_trades() -> list[dict]:
    client = _get_client()
    if client:
        try:
            resp = (client.table("paper_trades")
                    .select("*")
                    .order("placed_at", desc=False)
                    .execute())
            return resp.data or []
        except Exception as e:
            logger.warning(f"load_paper_trades failed: {e}")
    return _load_json(_PAPER_TRADES_JSON)


def add_paper_trade(trade: dict) -> None:
    """Insert one new paper trade. The 'id' field is auto-generated by Supabase."""
    client = _get_client()
    if client:
        row = {k: v for k, v in trade.items() if k != "id"}
        client.table("paper_trades").insert(row).execute()
        return
    trades = _load_json(_PAPER_TRADES_JSON)
    trades.append(trade)
    _save_json(_PAPER_TRADES_JSON, trades)


def mark_trade_as_placed(trade_id: str, order_id: str, bet_dollars: float = 0) -> None:
    """Mark a paper trade as placed on the exchange with order_id and bet amount."""
    updates = {
        "placement_status": "placed",
        "order_id": order_id,
        "placed_timestamp": datetime.now(timezone.utc).isoformat(),
        "updated_at": datetime.now(timezone.utc).isoformat(),
    }
    if bet_dollars > 0:
        updates["bet_dollars"] = bet_dollars
    client = _get_client()
    if client:
        try:
            client.table("paper_trades").update(updates).eq("id", trade_id).execute()
            return
        except Exception as e:
            logger.warning(f"mark_trade_as_placed failed: {e}")
    trades = _load_json(_PAPER_TRADES_JSON)
    for t in trades:
        if t.get("id") == trade_id:
            t.update(updates)
    _save_json(_PAPER_TRADES_JSON, trades)


def reopen_paper_trade(trade_id: str) -> None:
    """Reset a paper trade back to open (undoes an incorrect auto-settle)."""
    updates = {"status": "open", "result": None, "pnl_dollars": None}
    client = _get_client()
    if client:
        try:
            client.table("paper_trades").update(updates).eq("id", trade_id).execute()
            return
        except Exception as e:
            logger.warning(f"reopen_paper_trade failed: {e}")
    trades = _load_json(_PAPER_TRADES_JSON)
    for t in trades:
        if t.get("id") == trade_id:
            t["status"] = "open"
            t.pop("result", None)
            t.pop("pnl_dollars", None)
    _save_json(_PAPER_TRADES_JSON, trades)


def settle_paper_trade(trade_id: str, result: str, pnl: float) -> None:
    """Mark a paper trade settled with result + P&L. Matches by Supabase UUID id."""
    updates = {"status": "settled", "result": result, "pnl_dollars": pnl}
    client = _get_client()
    if client:
        try:
            client.table("paper_trades").update(updates).eq("id", trade_id).execute()
            return
        except Exception as e:
            logger.warning(f"settle_paper_trade failed: {e}")
    trades = _load_json(_PAPER_TRADES_JSON)
    for t in trades:
        if t.get("id") == trade_id:
            t.update(updates)
    _save_json(_PAPER_TRADES_JSON, trades)


# ── Position overrides ─────────────────────────────────────────────────────────
def load_position_overrides() -> dict[str, dict]:
    """Returns {ticker: {ticker, contracts, entry_cents, stop_cents}}"""
    local_rows = _load_json(_POSITIONS_JSON)
    local = {r["ticker"]: r for r in local_rows if isinstance(r, dict) and "ticker" in r}

    client = _get_client()
    if client:
        try:
            resp = client.table("position_overrides").select("*").execute()
            remote = {row["ticker"]: row for row in (resp.data or [])}
            for ticker, row in remote.items():
                if not row.get("entry_cents") and ticker in local:
                    row["entry_cents"] = local[ticker].get("entry_cents", 0)
                if not row.get("stop_cents") and ticker in local:
                    row["stop_cents"] = local[ticker].get("stop_cents", 0)
            return remote
        except Exception as e:
            logger.warning(f"load_position_overrides failed: {e}")
    return local


def save_position_overrides(overrides: dict[str, dict]) -> None:
    """Upsert all position overrides keyed by ticker."""
    client = _get_client()
    if client:
        try:
            now  = datetime.now(timezone.utc).isoformat()
            rows = [
                {
                    "ticker"      : ticker,
                    "contracts"   : data.get("contracts"),
                    "entry_cents" : data.get("entry_cents", 0),
                    "stop_cents"  : data.get("stop_cents", 0),
                    "placed_at"   : data.get("placed_at", now),
                    "updated_at"  : now,
                }
                for ticker, data in overrides.items()
            ]
            if rows:
                client.table("position_overrides").upsert(rows).execute()
            return
        except Exception as e:
            logger.warning(f"save_position_overrides failed: {e}")
    _save_json(_POSITIONS_JSON, list(overrides.values()))


# ── Calibration ────────────────────────────────────────────────────────────────
def load_calibration_db() -> dict | None:
    client = _get_client()
    if client:
        try:
            resp = (client.table("calibration")
                    .select("data")
                    .eq("id", 1)
                    .execute())
            if resp.data:
                return resp.data[0]["data"]
        except Exception as e:
            logger.warning(f"load_calibration_db failed: {e}")
    if _CALIBRATION_JSON.exists():
        import json
        with open(_CALIBRATION_JSON) as f:
            return json.load(f)
    return None


def save_calibration_db(data: dict) -> None:
    client = _get_client()
    if client:
        try:
            client.table("calibration").upsert({
                "id"        : 1,
                "data"      : data,
                "updated_at": datetime.now(timezone.utc).isoformat(),
            }).execute()
            return
        except Exception as e:
            logger.warning(f"save_calibration_db failed: {e}")
    _save_json(_CALIBRATION_JSON, data)


# ── Feature Flags ──────────────────────────────────────────────────────────
def load_feature_flags() -> dict:
    """Load feature flags (auto-placement toggles, etc) from Supabase."""
    defaults = {
        "auto_place_weekly": False,
        "auto_place_vol": False,
        "auto_place_intraday_short": False,
        "auto_place_intraday_long": False,
    }
    try:
        client = _get_client()
        resp = client.table("feature_flags").select("*").execute()
        if resp.data:
            return {row["key"]: row["value"] for row in resp.data}
        return defaults
    except Exception as e:
        logger.warning(f"Could not load feature flags from Supabase: {e}. Using defaults.")
        return defaults


def set_feature_flag(key: str, value: bool) -> None:
    """Set a feature flag value in Supabase."""
    try:
        client = _get_client()
        client.table("feature_flags").upsert({"key": key, "value": value}).execute()
    except Exception as e:
        logger.error(f"Could not set feature flag {key}={value}: {e}")


# ── Kalshi closed trades ───────────────────────────────────────────────────────
def load_kalshi_trades() -> list[dict]:
    """Load all non-excluded closed Kalshi positions from Supabase."""
    client = _get_client()
    if client:
        try:
            resp = (client.table("kalshi_trades")
                    .select("*")
                    .eq("excluded", False)
                    .order("settled_at", desc=True)
                    .execute())
            return resp.data or []
        except Exception as e:
            logger.warning(f"load_kalshi_trades failed: {e}")
    return []


def clear_kalshi_trades() -> None:
    """Delete all Kalshi trades (for backfill refresh)."""
    client = _get_client()
    if not client:
        return
    try:
        client.table("kalshi_trades").delete().gte("id", 0).execute()
        logger.info("Cleared all Kalshi trades")
    except Exception as e:
        logger.error(f"clear_kalshi_trades failed: {e}")


def upsert_kalshi_trades(trades: list[dict]) -> int:
    """Upsert closed positions keyed by (ticker, side). Returns count upserted."""
    if not trades:
        return 0
    client = _get_client()
    if not client:
        return 0
    try:
        now = datetime.now(timezone.utc).isoformat()
        rows = []
        for t in trades:
            rows.append({
                "ticker"        : t["ticker"],
                "side"          : t["side"],
                "asset"         : t.get("asset"),
                "strike"        : t.get("strike"),
                "expiry"        : t.get("expiry"),
                "week"          : t.get("week"),
                "contracts"     : t.get("contracts"),
                "entry_cents"   : t.get("entry_cents"),
                "exit_cents"    : t.get("exit_cents"),
                "buy_cost"      : t.get("buy_cost"),
                "sell_proceeds" : t.get("sell_proceeds"),
                "pnl"           : t.get("pnl"),
                "result"        : t.get("result"),
                "settled_at"    : t.get("settled_at"),
                "synced_at"     : now,
                "excluded"      : False,
            })
        client.table("kalshi_trades").upsert(rows, on_conflict="ticker,side").execute()
        return len(rows)
    except Exception as e:
        logger.warning(f"upsert_kalshi_trades failed: {e}")
        return 0


def exclude_kalshi_trade(ticker: str, side: str, excluded: bool = True) -> None:
    """Soft-delete (or restore) a trade from performance metrics."""
    client = _get_client()
    if client:
        try:
            client.table("kalshi_trades").update({"excluded": excluded}) \
                .eq("ticker", ticker).eq("side", side).execute()
        except Exception as e:
            logger.warning(f"exclude_kalshi_trade failed: {e}")


def get_latest_kalshi_trade_ts() -> str | None:
    """Return the most recent settled_at timestamp for incremental fill fetching."""
    client = _get_client()
    if client:
        try:
            resp = (client.table("kalshi_trades")
                    .select("settled_at")
                    .order("settled_at", desc=True)
                    .limit(1)
                    .execute())
            if resp.data:
                return resp.data[0]["settled_at"]
        except Exception as e:
            logger.warning(f"get_latest_kalshi_trade_ts failed: {e}")
    return None
